app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: DeviceOn 远程更新
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: code
      id: 1744019627790-source-1744019743416-target
      source: '1744019627790'
      sourceHandle: source
      target: '1744019743416'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: end
      id: 1744019743416-source-1744019871099-target
      source: '1744019743416'
      sourceHandle: source
      target: '1744019871099'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: api
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: api
        - label: token
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: token
        - label: timezone
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: timezone
        - label: question
          max_length: 80000
          options: []
          required: true
          type: paragraph
          variable: question
        - label: content
          max_length: 80000
          options: []
          required: true
          type: paragraph
          variable: content
        - label: type
          max_length: 80000
          options: []
          required: true
          type: paragraph
          variable: type
      height: 220
      id: '1744019627790'
      position:
        x: -24
        y: 282
      positionAbsolute:
        x: -24
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\nfunction main({}) {\n    return {\n        result: '目前暂不支持远程更新任务',\n\
          \        content: '',\n        type: '',\n        need_answer: 0,\n    }\n\
          }\n"
        code_language: javascript
        desc: ''
        outputs:
          content:
            children: null
            type: string
          need_answer:
            children: null
            type: number
          result:
            children: null
            type: string
          type:
            children: null
            type: string
        selected: true
        title: 代码执行
        type: code
        variables: []
      height: 54
      id: '1744019743416'
      position:
        x: 280
        y: 282
      positionAbsolute:
        x: 280
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1744019743416'
          - result
          variable: result
        - value_selector:
          - '1744019743416'
          - content
          variable: content
        - value_selector:
          - '1744019743416'
          - type
          variable: type
        - value_selector:
          - '1744019743416'
          - need_answer
          variable: need_answer
        selected: false
        title: 结束
        type: end
      height: 168
      id: '1744019871099'
      position:
        x: 584
        y: 282
      positionAbsolute:
        x: 584
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 199
      y: 24
      zoom: 1
